#!/bin/bash
rm /log/development.log 2>&1
rm /log/production.log 2>&1
git status
read -p "Press Enter "
git commit -a -m 'added'
read -p "Press Enter "
git push git@github.com:ionciubotaru/playlist.git
